# Generated by Django 3.1.6 on 2021-03-04 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210303_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueOn',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due On'),
        ),
    ]
